#!/bin/bash
if [ -z ${NM_ROOT+x} ]; then echo "source env.sh plz"; exit 1; fi

GT_VERSION=0.19.8.1
GT_PATH=$NM_SRC/gettext-$GT_VERSION
cd $GT_PATH

patch -p1 --forward < $NM_SCRIPT/gettext-patch

export ac_cv_header_langinfo_h=no

cd gettext-runtime
./configure --host=aarch64-linux-android --prefix=$NM_ROOT/out \
		   --disable-static \
		   --disable-libasprintf --disable-java --disable-native-java \
		   --without-emacs \
		   --disable-csharp \
		   --disable-openmp --disable-curses \
#		   --config-cache --cache-file $NM_SCRIPT/gettext-confcache

make -j8
make install

