#!/bin/bash
if [ -z ${NM_ROOT+x} ]; then echo "source env.sh plz"; exit 1; fi

NOTMUCH_VERSION=0.25.2
NOTMUCH_PATH=$NM_SRC/notmuch-$NOTMUCH_VERSION
cd $NOTMUCH_PATH

export XAPIAN_CONFIG=$NM_OUT/bin/xapian-config

$NOTMUCH_PATH/configure --prefix=$NM_ROOT/out --without-bash-completion --without-docs  --without-api-docs  --without-emacs  --without-desktop  --without-ruby  --without-zsh-completion
make install

