#!/bin/bash
if [ -z ${NM_ROOT+x} ]; then echo "source env.sh plz"; exit 1; fi

XAPIAN_VERSION=1.4.5
XAPIAN_PATH=$NM_SRC/xapian-core-$XAPIAN_VERSION
cd $XAPIAN_PATH

$XAPIAN_PATH/configure --prefix=$NM_ROOT/out --host=aarch64-linux-android --disable-shared --with-pic 

make install
